/**
 * Fetches the Declaration of Optimization from manual.warondisease.org
 * and generates a reusable Nunjucks include file.
 *
 * Usage: npx tsx scripts/generate-declaration-include.ts
 */

import * as https from "https";
import * as fs from "fs";
import * as path from "path";

const SOURCE_URL =
  "https://manual.warondisease.org/knowledge/strategy/declaration-of-optimization.html";
const CUTOFF_PHRASE = "This is suboptimal.";
const OUTPUT_PATH = path.join(
  __dirname,
  "..",
  "11ty",
  "_includes",
  "declaration-of-optimization.njk"
);

function fetchPage(url: string): Promise<string> {
  return new Promise((resolve, reject) => {
    https
      .get(url, (res) => {
        if (res.statusCode && res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
          return fetchPage(res.headers.location).then(resolve, reject);
        }
        let data = "";
        res.on("data", (chunk: Buffer) => (data += chunk.toString()));
        res.on("end", () => resolve(data));
        res.on("error", reject);
      })
      .on("error", reject);
  });
}

function extractContentHtml(html: string): string {
  // Remove script and style tags
  let cleaned = html.replace(/<script[\s\S]*?<\/script>/gi, "");
  cleaned = cleaned.replace(/<style[\s\S]*?<\/style>/gi, "");
  cleaned = cleaned.replace(/<nav[\s\S]*?<\/nav>/gi, "");
  cleaned = cleaned.replace(/<header[\s\S]*?<\/header>/gi, "");
  cleaned = cleaned.replace(/<footer[\s\S]*?<\/footer>/gi, "");

  // Try to find main content area
  const mainMatch =
    cleaned.match(/<main[\s\S]*?<\/main>/i) ||
    cleaned.match(/<article[\s\S]*?<\/article>/i);

  let content = mainMatch ? mainMatch[0] : cleaned;

  // Find the "Why This Declaration Is Necessary" heading and start after it
  const whyHeadingMatch = content.match(/<h[1-3][^>]*>[\s\S]*?Why This Declaration[\s\S]*?<\/h[1-3]>/i);
  if (whyHeadingMatch) {
    const idx = content.indexOf(whyHeadingMatch[0]);
    if (idx >= 0) {
      content = content.substring(idx + whyHeadingMatch[0].length);
    }
  } else {
    // Fallback: find any first heading about the declaration
    const headingMatch = content.match(/<h[1-3][^>]*>[\s\S]*?Declaration of Optimization[\s\S]*?<\/h[1-3]>/i);
    if (headingMatch) {
      const idx = content.indexOf(headingMatch[0]);
      if (idx > 0) {
        content = content.substring(idx + headingMatch[0].length);
      }
    }
  }

  // Truncate at cutoff phrase
  const cutoffIdx = content.indexOf(CUTOFF_PHRASE);
  if (cutoffIdx !== -1) {
    // Find the closing tag after the cutoff phrase
    const afterCutoff = content.substring(cutoffIdx);
    const closingTag = afterCutoff.match(/<\/p>|<\/div>/i);
    if (closingTag) {
      content = content.substring(0, cutoffIdx + closingTag.index! + closingTag[0].length);
    } else {
      content = content.substring(0, cutoffIdx + CUTOFF_PHRASE.length);
    }
  }

  // Strip confidence intervals: (95% CI: ...) patterns
  content = content.replace(/\s*\(95%\s*CI:\s*[^)]*\)/g, "");

  // Clean up parameter-link attributes — keep href and link text, strip data-* and title
  content = content.replace(/<a\s+[^>]*href='([^']*)'[^>]*>/gi, (match, href) => {
    // Make relative URLs absolute
    const fullHref = href.startsWith("/")
      ? `https://manual.warondisease.org${href}`
      : href;
    return `<a href="${fullHref}" target="_blank" rel="noopener">`;
  });

  // Strip citation superscript spans
  content = content.replace(/<span class="citation"[^>]*>[\s\S]*?<\/span>/gi, "");

  // Strip data-anchor-id and class from headings
  content = content.replace(/<(h[1-6])\s+[^>]*>/gi, "<$1>");

  // Remove keyword/metadata sections
  content = content.replace(/<p[^>]*>\s*Keywords[\s\S]*?<\/p>/gi, "");

  // Remove any remaining wrapper tags (main, article, section) but keep their content
  content = content.replace(/<\/?(main|article|section)[^>]*>/gi, "");

  // Clean up excessive whitespace
  content = content.replace(/\n{3,}/g, "\n\n");
  content = content.trim();

  return content;
}

function indent(html: string, spaces: number): string {
  const pad = " ".repeat(spaces);
  return html
    .split("\n")
    .map((line) => (line.trim() ? pad + line : ""))
    .join("\n");
}

function generateInclude(contentHtml: string): string {
  return `{# Auto-generated by scripts/generate-declaration-include.ts #}
{# Source: ${SOURCE_URL} #}
{# Re-run: npx tsx scripts/generate-declaration-include.ts #}

<section class="declaration-of-optimization">
  <div class="declaration-content">
    <h2>The Declaration of Optimization</h2>
${indent(contentHtml, 4)}

    <div class="declaration-cta">
      <a href="${SOURCE_URL}" target="_blank" rel="noopener noreferrer" class="declaration-button">
        Sign the Declaration of Optimization
      </a>
    </div>
  </div>
</section>
`;
}

async function main() {
  console.log(`Fetching ${SOURCE_URL}...`);
  const html = await fetchPage(SOURCE_URL);

  console.log("Extracting and cleaning content...");
  const contentHtml = extractContentHtml(html);

  console.log("Generating include...");
  const include = generateInclude(contentHtml);

  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
  fs.writeFileSync(OUTPUT_PATH, include, "utf-8");

  console.log(`Written to ${OUTPUT_PATH}`);
  console.log(`\nPreview (first 600 chars):\n${include.substring(0, 600)}...`);
}

main().catch((err) => {
  console.error("Error:", err);
  process.exit(1);
});
